// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:helm/core/analytics/data/models/nudge_preferences_model.dart';
import 'package:helm/core/analytics/models/analytics_event_model.dart';
import 'package:helm/core/nudge/data/models/nudge_log_entry_model.dart';
import 'package:helm/features/audit_log/data/models/audit_event_model.dart';
import 'package:helm/features/auth/data/models/session_model.dart';
import 'package:helm/features/income/data/models/income_model.dart';
import 'package:helm/features/safe_to_spend/data/models/fixed_cost_model.dart';
import 'package:helm/features/transactions/data/models/transaction_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnalyticsEventModelAdapter());
    registerAdapter(AuditEventModelAdapter());
    registerAdapter(FixedCostModelAdapter());
    registerAdapter(IncomeModelAdapter());
    registerAdapter(NudgeLogEntryModelAdapter());
    registerAdapter(NudgePreferencesModelAdapter());
    registerAdapter(SessionModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnalyticsEventModelAdapter());
    registerAdapter(AuditEventModelAdapter());
    registerAdapter(FixedCostModelAdapter());
    registerAdapter(IncomeModelAdapter());
    registerAdapter(NudgeLogEntryModelAdapter());
    registerAdapter(NudgePreferencesModelAdapter());
    registerAdapter(SessionModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
